### ISSUE TITLE
Data zip files corrupted

### ISSUE THREAD

**Issue by georgesim79** [LKchemposer/IsItRecyc-CNN#1]
Hi @LKchemposer. I just want to say I am happy you compiled this dataset, this was the dataset I have been looking for across the web. But for some reason I can't seem to extract the data zips. It gives the error "The archive is in unknown format or damaged" when I tried to extract "nonrecs" and "recs" zip files. 
I hope maybe you can check or reupload the zip files so I can extract them. Thanks!

**Comment by LKchemposer** [comment]
Hey @georgesim79, thanks for raising the issue, and for finding the dataset useful! I think it was one of the problems that arise from using git large file storage. I've now re-uploaded the zip files to a GDrive here: https://drive.google.com/drive/folders/1r3EiKldemvRvk2j9Dy68FekbDYfZLmf_?usp=sharing

Let me know if this works.
